env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    # https://github.com/eslint/eslint/blob/master/docs/rules/no-unused-vars.md
    - error
    -
      vars: 'all'
      varsIgnorePattern: '^_'
      args: 'all'
      ignoreRestSiblings: false
      argsIgnorePattern: '^_'
      caughtErrors: 'all'
      caughtErrorsIgnorePattern: '^_'
  ###=========================================================================
  ### "Possible Errors" rules
  ###=========================================================================
  for-direction:
    - error
  getter-return:
    - error
  no-await-in-loop:
    - error
  no-compare-neg-zero:
    - error
  no-cond-assign:
    - error
  no-console:
    - error
  no-constant-condition:
    - error
  no-control-regex:
    - error
  no-debugger:
    - error
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - error
  no-empty-character-class:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-parens:
    - off
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-inner-declarations:
    - error
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
  no-obj-calls:
    - error
  no-prototype-builtins:
    - error
  no-regex-spaces:
    - error
  no-sparse-arrays:
    - error
  no-template-curly-in-string:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unsafe-finally:
    - error
  no-unsafe-negation:
    - error
  use-isnan:
    - error
  # valid-jsdoc:
  valid-typeof:
    - error
    -
      requireStringLiterals: true
  ###=========================================================================
  ### "Best Practices" rules
  ###=========================================================================
  # accessor-pairs:
  array-callback-return:
    - error
  block-scoped-var:
    - error
  # class-methods-use-this:
  # complexity:
  consistent-return:
    - error
  curly:
    - error
    - multi-line
    - consistent
  default-case:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
  # guard-for-in:
  no-alert:
    - error
  no-caller:
    - error
  no-case-declarations:
    - error
  no-div-regex:
    - error
  no-else-return:
    - error
    -
      allowElseIf: false
  no-empty-function:
    - error
  no-empty-pattern:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-label:
    - error
  no-fallthrough:
    - error
  no-floating-decimal:
    - error
  no-global-assign:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - error
    -
      ignore: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      ignoreArrayIndexes: true
      enforceConst: true
      detectObjects: false
  no-multi-spaces:
    - error
    -
      ignoreEOLComments: true
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-octal:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
    -
      props: true
      ignorePropertyModificationsFor: []
  no-proto:
    - error
  no-redeclare:
    - error
  # no-restricted-properties:
  no-return-assign:
    - error
    - always
  no-return-await:
    - error
  no-script-url:
    - error
  no-self-assign:
    - error
    -
      props: true
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - error
  no-unused-expressions:
    - error
  no-unused-labels:
    - error
  no-useless-call:
    - error
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-useless-return:
    - error
  no-void:
    - error
  # no-warning-comments:
  no-with:
    - error
  prefer-promise-reject-errors:
    - error
  radix:
    - error
  require-await:
    - error
  vars-on-top:
    - off
  wrap-iife:
    - error
    - inside
  yoda:
    - error
    - never
    -
      exceptRange: true
      onlyEquality: false
overrides:
  files: ['main.js']
  env:
    node: false
    shared-node-browser: true
  parserOptions:
    sourceType: script
  globals:
    require: false
    module: false
    exports: false
    window: false
    global: false
    folktale: false
